spring:
  application:
    name: conan-admin
  datasource:
    url: jdbc:mysql://localhost:3306/conan
    username: root
    password: 123
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:conan-admin.yaml?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
