server:
  port: 8081
spring:
  application:
    name: conan-common
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:canon-common.properties?refreshEnabled=true
